services:
  client:
    image: vinivin153/movie-review-client:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  server:
    image: vinivin153/movie-review-server:latest
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
