services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server # 서버가 먼저 시작되도록 설정
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # Express 서버가 5000번 포트로 실행
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
