version: "3"
services:
  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "80:80" # Nginx가 80번 포트로 리액트 앱을 서빙
    depends_on:
      - server # 서버가 먼저 시작되도록 설정
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # Express 서버가 5000번 포트로 실행
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
